version: '3'
services:
 mongodb-container:
  image: mongo
  ports:
    - "27017:27017"
  volumes:
     - /var/mongodb/data:/data/db
  environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
 core-bank-api:
  image: zuhlke/core-bank-api:dev
  links:
    - mongodb-container
  ports:
    - "9090:9090"
 crowd-funding-api:
  image: zuhlke/crowd-funding-api:dev
  ports:
    - "9095:9095"
 robot-advisor-api:
  image: zuhlke/robot-advisor-api:dev
  ports:
    - "9096:9096"
 crowd-lending-api:
  image: zuhlke/crowd-lending-api:dev
  ports:
    - "9097:9097"
 insurance-api:
  image: zuhlke/insurance-api:dev
  links:
    - core-bank-api
  ports:
    - "9091:9091"
