/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.zuhlke.f10.insurance.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.zuhlke.f10.insurance.model.BuyerSpecifications;
import com.zuhlke.f10.insurance.model.Invoice;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.io.IOException;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-16T16:10:33.895+08:00")

@Api(value = "products", description = "the products API")
public interface ProductsApi {

    Logger log = LoggerFactory.getLogger(ProductsApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Buy Insurance", nickname = "pOSTProductsProductIdBuy", notes = "", response = Invoice.class, authorizations = {
        @Authorization(value = "Authorization"),
        @Authorization(value = "X-API-Key")
    }, tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "", response = Invoice.class) })
    @RequestMapping(value = "/products/{productId}/buy",
        method = RequestMethod.POST)
    ResponseEntity<Invoice> pOSTProductsProductIdBuy(@ApiParam(value = "", required = true) @PathVariable("productId") String productId, @ApiParam(value = "") @Valid @RequestBody BuyerSpecifications body);

}
