/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.zuhlke.f10.insurance.quotes.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.zuhlke.f10.insurance.model.*;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;
import java.math.BigDecimal;
import java.util.Optional;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-07-16T17:46:09.699+08:00")

@Api(value = "quotes", description = "the quotes API")
public interface QuotesApi {

    Logger log = LoggerFactory.getLogger(QuotesApi.class);

    default Optional<ObjectMapper> getObjectMapper() {
        return Optional.empty();
    }

    default Optional<HttpServletRequest> getRequest() {
        return Optional.empty();
    }

    default Optional<String> getAcceptHeader() {
        return getRequest().map(r -> r.getHeader("Accept"));
    }

    @ApiOperation(value = "Get Quotes", nickname = "pOSTQuotes", notes = "", response = Quotes.class, authorizations = {
        @Authorization(value = "Authorization"),
        @Authorization(value = "X-API-Key")
    }, tags={ "Quotes", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successful Response", response = Quotes.class),
        @ApiResponse(code = 400, message = "Bad Request", response = GenericError.class),
        @ApiResponse(code = 401, message = "Authentication Error", response = GenericError.class),
        @ApiResponse(code = 403, message = "Authorization Failed", response = GenericError.class),
        @ApiResponse(code = 500, message = "Internal Server Error", response = ServerError.class) })
    @RequestMapping(value = "/quotes/{productId}",
        method = RequestMethod.POST)
   ResponseEntity<QuoteDetails> getQuotes(@ApiParam(value = "",required=true) @PathVariable("productId") String productId, @ApiParam(value = ""  )  @Valid @RequestBody PolicyInfo body);


    }
